### ISSUE TITLE
ESP8266 Returns a zero IP ADdress

### ISSUE THREAD

**Issue by piwi1263** [MoleculeDotNet/Molecules#3]
Hi Martin,

when using the Oxygen in combination with Neon, the MAC is returned but the IP Address = 0.0.0.0.

The get time via sntp does work however, so connectivity to the internet is present.

Cheers, 

Peter.

**Comment by martincalsyn** [comment]
It looks like we have a valid IP address, but it just wasn't reported back to us. I am fixing this in two ways - 1) calling a routine to explicitly request the address information if it was not returned by the Connect command, and 2) providing a method called RefreshAddressInformation that you can use to query the chip for new address information. I doubt this is really needed because we query for address info on Connect, but it is one way to ensure you have the latest info. These will go in with the next checkin.

**Comment by piwi1263** [comment]
Looking forward to it ...

**Comment by martincalsyn** [comment]
Should be fixed now.
